version: '3'
services:
  timestamp-bot-ubuntu:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timestamp_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"