version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timestamp_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  selenium-chrome:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"   # Maps port 4444 on the host to port 4444 in the container
      - "7900:7900"   # Maps port 7900 on the host to port 7900 in the container
    shm_size: 2g     # Sets shared memory size to 2g
    depends_on:
      - mysql